version: "3"
services:
  web:
    build: ./web
    ports:
      - "80:80"
  
  api.graphql:
    build: ./api/graphql-server
    depends_on:
      - api.gateway
    links:
      - api.gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      API_URL: http://api.gateway:3000/api
  api.gateway:
    build: ./api/gateway
    expose:
      - "3000"
    depends_on:
      - api.resource
    links:
      - api.resource
  api.resource:
    build: ./api/resource
    depends_on:
      - db.postgres
    links:
      - db.postgres
    expose:
      - "4000"
    environment:
      PORT: 4000
      DATABASE_PASSWORD: example
      DATABASE_HOST: db.postgres:5432

  db.mongo:
    image: mongo:3.4
  db.postgres:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: example