version: "3"
services:
  web:
    build: ./web
    ports:
      - "80:80"
    links:
      - api-gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    links:
      - auth01
      - auth02
  auth01:
    build: ./api/auth
    links:
      - api-db
    volumes:
      - ./api/auth:/api
  auth02:
    build: ./api/auth
    links:
      - api-db
    volumes:
      - ./api/auth:/api
  api-db:
    build: ./api/mongo-api
    volumes:
      - ./api/mongo-api/db:/data/db/