version: "3"
services:
  web:
    build: ./web
    ports:
      - "80:80"
    links:
      - api.gateway
  api.gateway:
    build: ./api/proxy
    ports:
      - "3000:3000"
  api.resource:
    build: ./api/resource
    links:
      - db.mysql
    volumes:
      - ./api/resource:/api
  db.mongo:
    build: ./db/mongo
    volumes:
      - ./db/mongo/data:/data/db/