version: "3"
services:
  web:
    build: ./web
    ports:
      - "80:80"
  
  api.gateway:
    build: ./api/gateway
    depends_on:
      - api.proxy
    links:
      - api.proxy
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      API_URL: http://api.proxy:3000/api
  api.proxy:
    build: ./api/proxy
    expose:
      - "3000"
    depends_on:
      - api.resource1
      - api.resource2
      - api.resource3
    links:
      - api.resource1
      - api.resource2
      - api.resource3
  api.resource1:
    build: ./api/resource
    depends_on:
      - db.postgres
    links:
      - db.postgres
    expose:
      - "4000"
    environment:
      PORT: 4000
      DATABASE_PASSWORD: example
      DATABASE_HOST: db.postgres:5432
  api.resource2:
    build: ./api/resource
    depends_on:
      - db.postgres
    links:
      - db.postgres
    expose:
      - "4000"
    environment:
      PORT: 4000
      DATABASE_PASSWORD: example
      DATABASE_HOST: db.postgres:5432
  api.resource3:
    build: ./api/resource
    depends_on:
      - db.postgres
    links:
      - db.postgres
    expose:
      - "4000"
    environment:
      PORT: 4000
      DATABASE_PASSWORD: example
      DATABASE_HOST: db.postgres:5432

  db.mongo:
    image: mongo:3.4
  db.postgres:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: example