version: "3"
services:
  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "80:80"
    links:
      - api
  api:
    build: ./api-gateway
    depends_on:
      - api-db
    ports:
      - "3000:3000"
    links:
      - api-db
    environment:
      DATABASE_URL: mongodb://api-db:27017
      TOKEN_SECRET: qwert1234
    volumes:
      - ./api-gateway/:/api
  api-db:
    image: mongo:3.4
    expose:
      - "27017"
    volumes:
      - ./api-gateway/db/:/data/db/