version: '3'
services:
  server-proxy:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - api
  web:
    build: ./angular
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./nodejs
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db