version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./api-gateway
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"