version: '3'
services:
  server-proxy:
    build: ./server-proxy
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - api-gateway
  api-gateway:
    build: ./api-gateway
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db