version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./api-gateway
    depends_on:
      - api-db
    ports:
      - "3000:3000"
    links:
      - api-db
    environment:
      DATABASE_URL: mongodb://api-db:27017
      TOKEN_SECRET: qwert1234
  api-db:
    image: mongo:3.4
    expose:
      - "27017"